partB:
	javac -cp ".:libthrift-0.9.1.jar:slf4j-api-1.7.12.jar" Account.java BankServiceConstants.java BankService.java ClientHandler.java BankClient.java BankServer.java	

clean:
	$(RM) *.class

default: partB
